package ru.practicum.shoppinglist.feature.lists.ui

enum class AppIconKey(val value: String) {
    SHOPPING_CART("shopping_cart"),
    SHOPPING_BAG("shopping_bag"),
    LOCAL_FLORIST("local_florist"),
    CONSTRUCTION("construction"),
    CELEBRATION("celebration"),
    CAKE("cake"),
    REDEEM("redeem"),
    LIQUOR("liquor"),
    PETS("pets"),
    TEMPLE("temple"),
    MEDICATION("medication"),
    SCHOOL("school"),
    SNOWBOARDING("snowboarding"),
    HOME("home"),
    FITNESS_CENTER("fitness_center"),
    CHILD_CARE("child_care"),
    ESPORTS("esports"),
    PALETTE("palette"),
    APPAREL("apparel"),
    DIRECTIONS_CAR("directions_car"),
    LUGGAGE("luggage"),
    CHAIR("chair"),
    SPA("spa"),
    PHOTO_CAMERA("photo_camera"),
    IMPORT_CONTACTS("import_contacts"),
    SELF_IMPROVEMENT("self_improvement"),
    TOYS("toys"),
    DEVICES("devices"),
    STROLLER("stroller"),
    LIST_ALT("list_alt"),
}
